networks:
  api-network:
    driver: bridge
  static-network:
    ipam:
      config:
        - subnet: 172.19.0.0/23

services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    command: sh /api/start.sh
    ports:
      - "8000:8000"
    networks:
      - api-network
      - static-network
    volumes:
    - ${PWD}/data:/api/data

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.2
    container_name: es
    restart: always
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xms512M -Xmx512M"
    ports:
      - "9200:9200"
    healthcheck:
      test:
        - "CMD-SHELL"
        - "curl --silent --fail localhost:9200/_cluster/health || exit 1"
      interval: 10s
      timeout: 10s
      retries: 3
    volumes:
      - ${PWD}/data:/usr/share/elasticsearch/data
    networks:
      - api-network
      - static-network
