networks:
  api-network:
    driver: bridge
  static-network:
    ipam:
      config:
        - subnet: 172.19.0.0/23

services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    # command: python -m manage runserver 0.0.0.0:8000
    command: sleep 5000
    ports:
      - "8000:8000"
    networks:
      - api-network
      - static-network
    volumes:
      - ./data:/api/data